#!/usr/bin/env python3
"""Generate SYNTHETIC (simulated) demo fixtures for the STEM-Alt pipeline.

============================================================================
SYNTHETIC DEMO DATA - NOT A MEASURED RESULT.
============================================================================

This script fabricates *clearly-labelled* placeholder data so the pipeline and
the evaluation-figure renderer can be exercised end to end before the real
human study has been run. It is the data-level counterpart of the repository's
test doubles.

The outputs illustrate the *format and plumbing*, not any finding. No human
rated these figures, no critic was trained, and no Krippendorff alpha was
computed from real data. The numbers must never be cited, never be written into
`paper/` or `README.md`, and never be presented as the held-out evaluation
result. When the real study runs, replace these files with the genuine ratings
ledger and the genuine `code/outputs/<run>/held_out_report.json`.

Outputs (every artefact is marked SIMULATED):
    data/ratings/ratings_SIMULATED.jsonl   two synthetic raters per held-out figure
    demo/held_out_report_SIMULATED.json    synthetic convergence trace + held-out pairs
    demo/README.md                         what these files are and are not

Determinism: seeded (default 20260604); re-running reproduces identical output.
Dependencies: Python standard library only.

Usage:
    python code/scripts/generate_synthetic_ratings.py [--seed 20260604]
"""
from __future__ import annotations

import argparse
import csv
import json
import logging
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
LOGGER = logging.getLogger("generate_synthetic_ratings")

BANNER = (
    "SIMULATED DEMO DATA - generated by code/scripts/generate_synthetic_ratings.py. "
    "NOT a measured result. Do not cite. Replace with the real study output before "
    "any release claim. See demo/README.md."
)

# code/scripts/ -> code/ -> project work/
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "data" / "corpus" / "manifest.csv"
RATINGS_OUT = ROOT / "data" / "ratings" / "ratings_SIMULATED.jsonl"
DEMO_DIR = ROOT / "demo"
REPORT_OUT = DEMO_DIR / "held_out_report_SIMULATED.json"

# Designed, illustrative convergence trace (NOT measured). alpha_primary is
# computed below as mean(D1, D2, D3) so the curve and the per-dimension bars stay
# internally consistent. It crosses 0.70 at r=3 and holds at r=4 (the
# pre-registered "sustained over two consecutive rounds" criterion).
ROUND_DIMS: list = [
    # r, (D1, D2, D3, D4, D5), mean_abs_delta
    (0, (0.40, 0.39, 0.44, 0.52, 0.55), 1.05),
    (1, (0.54, 0.52, 0.58, 0.63, 0.66), 0.82),
    (2, (0.63, 0.61, 0.67, 0.71, 0.74), 0.63),
    (3, (0.70, 0.69, 0.74, 0.79, 0.82), 0.50),
    (4, (0.73, 0.72, 0.76, 0.83, 0.86), 0.43),
]
FINAL_ROUND = ROUND_DIMS[-1][0]

# The critic underrates harder categories; this drives the residual heatmap.
CATEGORY_RESIDUAL = {"simple": 0.18, "linked": 0.28, "decorative": 0.30, "complex": 0.58}
CATEGORY_BIAS = {"simple": -0.05, "linked": -0.12, "decorative": -0.10, "complex": -0.35}

CRITIQUE = {
    "domain_expert": "[SYNTHETIC DEMO] Placeholder domain-expert critique.",
    "screen_reader_user": "[SYNTHETIC DEMO] Placeholder screen-reader-user critique.",
}


def clip(x: float, lo: float = 1.0, hi: float = 5.0) -> float:
    """Clamp ``x`` to the inclusive range [lo, hi]."""
    return max(lo, min(hi, x))


def load_held_out() -> list[dict[str, str]]:
    """Load the held-out split rows from the corpus manifest, sorted by id."""
    with MANIFEST.open(newline="", encoding="utf-8") as fh:
        rows = [r for r in csv.DictReader(fh) if r["split"] == "held_out"]
    rows.sort(key=lambda r: r["figure_id"])
    return rows


def build_rounds() -> list[dict]:
    """Build the illustrative per-round convergence trace."""
    rounds = []
    for r, dims, delta in ROUND_DIMS:
        per_dim = {f"D{i + 1}": round(dims[i], 2) for i in range(5)}
        alpha_primary = round((dims[0] + dims[1] + dims[2]) / 3.0, 3)
        rounds.append({
            "r": r,
            "alpha_primary": alpha_primary,
            "alpha_per_dim": per_dim,
            "mean_abs_delta": delta,
        })
    return rounds


def rater_score(rng: random.Random, quality: float, role: str) -> dict:
    """Return a synthetic five-dimension score centred on a latent quality."""
    score: dict = {}
    for dim in ("D1_factual_correctness", "D2_information_sufficiency", "D3_domain_accuracy"):
        score[dim] = int(clip(round(quality + rng.gauss(0, 0.45))))
    # D4 (no fabrication) and D5 (length compliance) tend to score higher.
    for dim in ("D4_hallucination", "D5_conciseness"):
        score[dim] = int(clip(round(quality + 0.6 + rng.gauss(0, 0.40))))
    score["critique"] = CRITIQUE.get(role, "[SYNTHETIC DEMO] Placeholder critique.")
    return score


def primary_mean(score: dict) -> float:
    """Return the primary outcome, the mean of D1, D2 and D3."""
    return (
        score["D1_factual_correctness"]
        + score["D2_information_sufficiency"]
        + score["D3_domain_accuracy"]
    ) / 3.0


def main() -> None:
    """Generate the synthetic ratings ledger and held-out report, then write them."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--seed", type=int, default=20260604)
    args = parser.parse_args()
    rng = random.Random(args.seed)

    held = load_held_out()
    base_ts = datetime(2026, 4, 20, 9, 0, 0, tzinfo=timezone.utc)

    ratings: list[dict] = []
    held_out_pairs: list[dict] = []
    for idx, row in enumerate(held):
        fid, domain, cat = row["figure_id"], row["domain"], row["eth_category"]
        quality = clip(rng.gauss(3.7, 0.55))
        human_primaries = []
        for j, (role, nvda) in enumerate(
            (("domain_expert", False), ("screen_reader_user", True))
        ):
            score = rater_score(rng, quality, role)
            human_primaries.append(primary_mean(score))
            ts = (base_ts + timedelta(hours=idx * 3 + j)).isoformat().replace("+00:00", "Z")
            ratings.append({
                "figure_id": fid,
                "rater_id": f"SIM-{'EXP' if role == 'domain_expert' else 'SR'}-{idx + 1:02d}",
                "rater_role": role,
                "candidate_round": FINAL_ROUND,
                "score": score,
                "rendered_via_nvda": nvda,
                "timestamp": ts,
                "synthetic": True,
            })
        h_primary = round(sum(human_primaries) / len(human_primaries), 2)
        c_primary = round(
            clip(quality + CATEGORY_BIAS[cat] + rng.gauss(0, CATEGORY_RESIDUAL[cat])), 2
        )
        held_out_pairs.append({
            "figure_id": fid,
            "domain": domain,
            "eth_category": cat,
            "c_primary": c_primary,
            "h_primary": h_primary,
        })

    report = {
        "_SYNTHETIC": BANNER,
        "_seed": args.seed,
        "rounds": build_rounds(),
        "held_out": held_out_pairs,
    }

    RATINGS_OUT.parent.mkdir(parents=True, exist_ok=True)
    DEMO_DIR.mkdir(parents=True, exist_ok=True)
    with RATINGS_OUT.open("w", encoding="utf-8") as fh:
        for rec in ratings:
            fh.write(json.dumps(rec) + "\n")
    REPORT_OUT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (DEMO_DIR / "README.md").write_text(DEMO_README, encoding="utf-8")

    LOGGER.info("Wrote %d synthetic ratings -> %s", len(ratings), RATINGS_OUT.relative_to(ROOT))
    LOGGER.info(
        "Wrote synthetic held-out report (%d figures, seed=%d) -> %s",
        len(held_out_pairs), args.seed, REPORT_OUT.relative_to(ROOT),
    )
    LOGGER.warning("SYNTHETIC DEMO DATA - not a measured result.")


DEMO_README = """# `demo/` - SYNTHETIC pipeline fixtures (NOT results)

> **Everything in this directory and in `../data/ratings/ratings_SIMULATED.jsonl`
> is simulated placeholder data**, generated by
> `code/scripts/generate_synthetic_ratings.py` (seed 20260604). It exists so the
> pipeline and the evaluation-figure renderer can be exercised end to end before
> the real human study is run. It is the data-level counterpart of the repo's
> test doubles.

**These numbers are not a measured result.** No human rated these figures, no
critic was trained, and no Krippendorff alpha was computed from real data. Do
not cite them, do not put them in `paper/` or `README.md`, and do not present
them as the held-out evaluation outcome.

## Files

- `held_out_report_SIMULATED.json` - a simulated held-out report in the exact
  schema `pipeline/05_evaluate.py` emits (`rounds` + `held_out`), with a
  `_SYNTHETIC` banner key.
- `figures/` - the four evaluation figures rendered from the simulated report,
  for layout and plumbing preview only.
- `../data/ratings/ratings_SIMULATED.jsonl` - two simulated raters per held-out
  figure, schema-valid per `data/ratings/README.md`, every line tagged
  `"synthetic": true`, every critique prefixed `[SYNTHETIC DEMO]`.

## Regenerate

```bash
python code/scripts/generate_synthetic_ratings.py        # writes the JSONL + report

# render the four demo figures into demo/figures/ (needs the analysis deps):
code/.venv/bin/python - <<'PY'
import importlib.util, json, pathlib
spec = importlib.util.spec_from_file_location("ef", "analysis/generate_eval_figures.py")
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
m.render_all(json.load(open("demo/held_out_report_SIMULATED.json")), pathlib.Path("demo/figures"))
PY
```

## Replacing with the real study

When the real study runs, `pipeline/05_evaluate.py` writes a genuine
`code/outputs/<run>/held_out_report.json` from real loop traces and a real
`ratings_*.jsonl`. Render the real figures from that report, then delete this
`demo/` directory and `data/ratings/ratings_SIMULATED.jsonl`. Only then may the
figures and the convergence alpha be described as findings.
"""


if __name__ == "__main__":
    main()
