"""Build publication-ready table inputs from the corpus manifest.

Emits Excel workbooks that `pubtab xlsx2tex` converts into booktabs-style
LaTeX tables for the manuscript and supplementary material:

    tables/corpus_stratification.xlsx   domain x ETH category census (paper Table 1)
    tables/corpus_composition.xlsx      DIAGRAM figure-type and source-licence counts

Every number is derived from `data/corpus/manifest.csv`; the workbooks are
intermediate build inputs, regenerated by this script.

Usage:
    python analysis/make_publication_tables.py
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
LOGGER = logging.getLogger("make_publication_tables")

HERE = Path(__file__).resolve().parent
MANIFEST = HERE.parent / "data" / "corpus" / "manifest.csv"
TABLE_DIR = HERE.parent / "manuscript" / "tables"

CATEGORY_ORDER = ["simple", "linked", "decorative", "complex"]
DOMAIN_ORDER = ["chemistry", "mathematics_cs", "biology", "physics"]
DOMAIN_LABELS = {
    "chemistry": "Chemistry",
    "mathematics_cs": "Mathematics and CS",
    "biology": "Biology",
    "physics": "Physics",
}


def stratification_table(df: pd.DataFrame) -> pd.DataFrame:
    cross = pd.crosstab(df["domain"], df["eth_category"])
    cross = cross.reindex(index=DOMAIN_ORDER, columns=CATEGORY_ORDER, fill_value=0)
    cross.index = [DOMAIN_LABELS[d] for d in cross.index]
    cross["Total"] = cross.sum(axis=1)
    cross.loc["Total"] = cross.sum(axis=0)
    out = cross.reset_index().rename(columns={
        "index": "Domain", "simple": "Simple", "linked": "Linked",
        "decorative": "Decorative", "complex": "Complex",
    })
    return out


def composition_table(df: pd.DataFrame) -> pd.DataFrame:
    dtypes = (df["diagram_type"].value_counts()
              .rename_axis("Category").reset_index(name="Count"))
    dtypes.insert(0, "Axis", "DIAGRAM figure type")
    lics = (df["licence"].value_counts()
            .rename_axis("Category").reset_index(name="Count"))
    lics.insert(0, "Axis", "Source licence")
    return pd.concat([dtypes, lics], ignore_index=True)


def main() -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(MANIFEST, dtype=str).fillna("")
    LOGGER.info("Loaded %d figures", len(df))

    strat = stratification_table(df)
    strat.to_excel(TABLE_DIR / "corpus_stratification.xlsx", index=False)
    LOGGER.info("Wrote tables/corpus_stratification.xlsx (%d rows)", len(strat))

    comp = composition_table(df)
    comp.to_excel(TABLE_DIR / "corpus_composition.xlsx", index=False)
    LOGGER.info("Wrote tables/corpus_composition.xlsx (%d rows)", len(comp))


if __name__ == "__main__":
    main()
